global CavityChoice MethodChoice;
global SpheroidDomain RegularMesh;
global VORTEX;
global start_time;
global Prec;
global Node_Num Edge_Num Element_Num Free_Num;
global Gauss Gauss_T Gauss_T2;
global G0 M0 w0 Fea_Len Gause;
global Ae Be Ce De;
global A B C D;
global e_value e_vector;
global G;
global node element td;
global t_g t_p t_e t_t;
global R H;
global W0 a0;
global alpha;
global P0 Z0 r1 r2 h1 h2;
global nodes nodes_x nodes_y;
global tx ty nx ny dx dy sx sy ta tb tc ts xc yc len nr e_type boundary;
global free_point free_edge distance;
global b_init_matrix d_init_matrix;
global t_x t_y;

global A11;
global B11 B12 B21 B22;
global C11 C12 C21 C22;
global D11 D12 D21 D22;
global a41 a42 a43 a44 a45;
global a61 a62 a63 a64 a65;

global s_mode s_freq;
global u_mode u_freq;
global freq_d freq_c;
global H_mesh H_spectrum;
global B_mesh B_spectrum;